
# About the project

*Write a short description about the course and add a link to your GitHub repository here. This is an R Markdown (.Rmd) file so you should use R Markdown syntax.*

I am a phD student working on rare kidney diseases and immunology. I have followed some specific R courses rather for medical studies which allowed to apply the newly learned R functions for my research work. I would like to broaden my knowledge in the use of R which are not specifically related to my topic. The content of the course looked to me completely new and interesting so I am happy to learn more about open science, open data,  data science. I expect to get insight in the coding, the analysis and the interpretation of of regression and model validation, Data wrangling, clustering and classification.

https://github.com/Julia1756/IODS-project.git

```{r}
# This is a so-called "R chunk" where you can write R code.

date()

```
The text continues here.


Going through R gor health Data science was an insightful learning of R basics and its different functionalities.The content is very didactive. My favorite part was the R basics because I never had the opportunity to take time for learning the basics in depth. I also liked the part allowing to plot different kind of graphs. The most difficult part might be "summarizing data".
